version: "3.7"

networks:
  stock-network:
    driver: bridge

services:
  stock-analyzer:
    build:
      context: .
      dockerfile: stock_analyzer/Dockerfile
    depends_on:
      - kafka
      - stock-config
    image: stock-analyzer:0.1
    networks:
      - stock-network
    environment:
      - CONFIG_HOST=stock-config
      - MESSAGE_QUEUE_TYPE=kafka
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=stock-quotes
  stock-query:
    build:
      context: .
      dockerfile: stock_query/Dockerfile
    depends_on:
      - kafka
      - stock-config
    image: stock-query:0.1
    networks:
      - stock-network
    environment:
      - CONFIG_HOST=stock-config
      - MESSAGE_QUEUE_TYPE=kafka
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=stock-quotes
  stock-config:
    image: bitnami/etcd:3.4.7
    networks:
      - stock-network
    ports:
      - '2379:2379'
      - '2380:2380'
    volumes:
      - '.etcd_data:/bitnami/etcd'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
  kafka:
    hostname: kafka
    depends_on:
      - zookeeper
    image: kafka-jmx:0.1
    networks:
      - stock-network
    ports:
      - '9092:9092'
      - '9992:9992'
      - '29092:29092'
    volumes:
      - '.kafka:/bitnami'
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      # - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      # - KAFKA_ZOOKEEPER_USER=kafka
      # - KAFKA_ZOOKEEPER_PASSWORD=kafka-password
      # - KAFKA_BROKER_USER=stock
      # - KAFKA_BROKER_PASSWORD=stock
  zookeeper:
    image: bitnami/zookeeper:3.6.1
    networks:
      - stock-network
    ports:
      - '2181:2181'
    volumes:
      - '.zookeeper:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      # - ZOO_ENABLE_AUTH=yes
      # - ZOO_SERVER_USERS=kafka
      # - ZOO_SERVER_PASSWORDS=kafka-password
  telegraf:
    image: telegraf:1.14.3
    networks:
      - stock-network
    volumes:
      - './conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
  influxdb:
    image: bitnami/influxdb:1.8.0
    networks:
      - stock-network
    volumes:
      - '.influxdb:/bitnami/influxdb'
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER_PASSWORD=influxdb-password
      # - INFLUXDB_DB=stock
      # - INFLUXDB_USER=appuser
      # - INFLUXDB_USER_PASSWORD=influxdb-password
  grafana:
    image: bitnami/grafana:6.7.3
    networks:
      - stock-network
    ports:
      - '9997:3000'
    volumes:
      - '.grafana_data:/opt/bitnami/grafana/data'
