image:
  repo: marketplace.gcr.io/google/etcd
  tag: 3.3
replicas: 3
service:
  dnsBase: svc.cluster.local
  type: ClusterIP
  port: 2379
  peerPort: 2380
persistence:
  storageClass: data
  size: 1Gi
metrics:
  image: marketplace.gcr.io/google/etcd/prometheus-to-sd:3.3
  exporter:
    enabled: true
